### ISSUE TITLE
Shared Albums Won't Disappear

### ISSUE THREAD

**Issue by sloandidit** [chtaylo2/Roku-GooglePhotos#112]
Shared albums are appearing now... but they won't go away even after the person who shared them unshared or after I leave the shared folder.  They are stuck forever cluttering up my albums on PhotoView, but don't appear anywhere in GooglePhotos any longer.  LOL

Thank you!

**Comment by chtaylo2** [comment]
Current shared album implementation in Google photos, is not present. You're likely looking at legacy sharing from Picasa. Even so, the API only returns albums associated to your account.

One of your shared photos, if you search the file name in Google Photos desktop client, does it appear?

**Comment by LibraSun** [comment]
Yes, this is happening to me and I'm steadily being driven crazy by it. After six hours of trying to identify where the images and folders originate (Shared? No. In Google Drive? Maybe. Trash? Sometimes. Google Photos? Nah. Gmail? Once. Sites? Really? Picasa? Lord, how?), I'm about to give up. Tried deleting whatever matches I find yet no impact on Photoview display, sadly.
Understand per above response that API is handing off all these extra folders, but I can safely say I only have a single Google Photos album (shows up fine), while the others make zero sense. Searching everywhere for exact filenames not helping.

**Comment by LibraSun** [comment]
UPDATE: OMG, I was wrong ♪ it was Picasa all along... 
I wound up visiting https://get.google.com/albumarchive (the repository for all long-abandoned Picasa Web Albums), and lo and behold! There they all were. All 32 of the damn things.
Clicking one-by-one and choosing ... DELETE ALBUM cured me of this plague. 

I hope this feedback helps others stuck in the same boat.

NOTE: You cannot reasonably DELETE "Profile Photos" because that album apparently contains the image file(s) you associated with ALL of your Google services. Why this one gets displayed in PhotoView at all is fodder for another discussion. Just as an apparent mismatch between how many images (694) PhotoView's main screen indicates are contained in "Timeline" versus the actual count (16) is a subject for a different Open Issue.

Keep up the great work!

**Comment by LibraSun** [comment]
NEXT UPDATE: By locating the unwanted photos in Google Photos app > Archive, and selecting them individually (or as a group), then sending them to Trash, I was successful in stopping PhotoView from displaying them as Albums on Roku. In fact, after each "Trash" operation, I tested PhotoView by first backing out of any Album, then attempting to view the "Trashed" Album again, which would cause PhotoView to exit spontaneously to the Roku "Home" screen. Upon re-entering PhotoView, the offending Album was gone. I repeated this for each and every unwanted Album (except "Profile", which I fear deleting would erase my profile avatar from every Google app).
