### ISSUE TITLE
*** MEDIA NOT DISPLAYING? -- READ HERE ***

### ISSUE THREAD

**Issue by chtaylo2** [chtaylo2/Roku-GooglePhotos#187]
Google gives this application a quota on how many items it can pull from the Google Photos service daily. As this channel just moved to the new API - March 15, 2019 - we are evaluating the overall demand and negotiating this quota with Google.

If your images/videos do not appear, please try again tomorrow. Thanks

**Comment by rezaahmadi65** [comment]
Thanks for the great app.  It's one of the most useful roku channels.  However the new hourly limit on the screen saver function greatly reduces the functionality of the app.  My suggestion is that instead of enforcing a time limit, enforce a limit on the number of photos that each roku device can pull from the google photos service per 24 hours.  This can be easily implemented by enforcing a lower limit on the slide show delay time.  For example, by making the lowest delay time possible 5 minutes, the roku device will only pull 24*60/12=120 pictures for each 24 hours.  This will make the screen saver function useful again and also limit the pulled data.

**Comment by chtaylo2** [comment]
@rezaahmadi65 -- Thanks for the feedback and suggestion. I like the idea. Unfortunately, the time based approach was the quickest to add in short notice. I'll look to move to a rate-limited type approach in an upcoming release.  See: #190

**Comment by rezaahmadi65** [comment]
Thanks for getting back to me.  Looking forward to the upcoming release

**Comment by norrisc761** [comment]
Any news on this issue yet?

**Comment by chtaylo2** [comment]
They increased it last week by 5x what we originally were given, however still not enough. We requested additional on Monday and still waiting to hear back.

**Comment by ytzeng1** [comment]
Hi, I just recently discovered your channel and I really like it. However, as I started to upload my local photo library to my google account, the channel cannot load any of my images and only show up a black screen. I switched to a different google account and it's the same thing. Is there a certain amount of photos that the app can load? Thank you very much!

**Comment by armandofox** [comment]
No photos are displaying, thumbnails or otherwise, in any view, anywhere, ever. that means the app fails to fulfill its only goal, which is to display photos. note i have not opened the app in weeks and have not uploaded very many photos to google itself. has the app become a brick?
