### ISSUE TITLE
Feature Request: Display a Single Image Indefinitely

### ISSUE THREAD

**Issue by AJDesignCo** [chtaylo2/Roku-GooglePhotos#297]
I just attempted to use this app to display one image as a static title message for an hour-long presentation. I used the "Browse" option rather than the "Slideshow" option. It seemed to display the single image for a period of time, but then the app started a slideshow of images from the other albums in my account.

I don't know if this is operator error or a development issue, but it would be nice if the app had an option to display a single image indefinitely without moving to a different image or album.

Thanks!

**Comment by chtaylo2** [comment]
This is by design as we’re not allowed to block the Roku screensaver when not in a “user initiated slideshow”. Ie: you paused it or only 1 image which effectively pauses it.

Easy fix though, just disable your screensaver when doing a presentation like this and it shouldn’t kick on over top of your display.
