### ISSUE TITLE
Feature Request: Update album cache without restarting screensaver

### ISSUE THREAD

**Issue by smiles3983** [chtaylo2/Roku-GooglePhotos#300]
I would like to be able to have the screensaver running, add new photos to my album, and see them show up on the screensaver without having to exit and restart.  I have had the screen saver on during my kids birthday parties, and I like it when my photos show up right away for people to see them.

**Comment by chtaylo2** [comment]
@smiles3983 - When you have the "Time in History" albums selected, it will refresh because of how the API searching functions. About once an hour. However, while the feature you listed would be cool, its not doable because of API quotas. Google limits our API calls, which is required for album refreshes, so not able to automatically do this without sky rocketing our quota usage.
