### ISSUE TITLE
Max # of photos per album?

### ISSUE THREAD

**Issue by dsscskin** [chtaylo2/Roku-GooglePhotos#301]
Is 1000 photos the maximum number that can be placed in any album? I have an album with over 1000 and My question is, does Photoview just show the first thousand and ignore the rest?

**Comment by chtaylo2** [comment]
You can have unlimited photos per album, however in "SLIDESHOW" mode, it only pulls between 900 - 1,200 images per album. There's no exact number because of how Google's API works.

In normal slideshows in the Channel, you can move to additional pages in the album to pull your next set of 900 - 1,200 photos.
