### ISSUE TITLE
Unable to load 4K photos on Roku Premiere+

### ISSUE THREAD

**Issue by nrobins** [chtaylo2/Roku-GooglePhotos#304]
In the global settings I select the UHD 4K resolution for photos. However, they don't display at that resolution on the TV screen; the details are fuzzy. I have uploaded the photos at original resolution to Google Photos. I can compare the image with the Photo and Video app on my LG 4K TV from a local copy or compare with Chrome browser on my Apple Retina display laptop loading the file from the Google photos account and the detail is sharp. Let me know what other information you need. I can share an album with you if you want to see it.

**Comment by hbmcmahan** [comment]
I'm hitting this issue as well, I verified I'm not getting UHD 4K by displaying this test image:
https://drive.google.com/file/d/0B4ijp-kf8RV0dVFORnppbW1mQ0E/view
The image clearly displays with a flat gray background rather than a black & white grid. This is also on an LG 4K TV. I'd really like to get to the bottom of this, displaying 4K photos with PhotoView was the main reason I bought a Roku.

**Comment by chtaylo2** [comment]
When the photo url's are requested from Google's API, the app gives it a size resolution to pull back. You can see a reference to those sizes here:
https://github.com/chtaylo2/Roku-GooglePhotos/blob/master/components/Utils/Common.brs#L315-L318

I confirmed that when I have my setting to UHD, the photo coming back from Google API is in fact W3840 x H2160.   I confirmed this on my Mac by manually downloading the photo.

So Google Photos (not PhotoView app) does in fact, resize photos through some algorithm they have. It may cause very minor distortion to a photo, though I've been using it on 4K TV's for years and have never noticed.

**Comment by hbmcmahan** [comment]
Thanks for the quick reply, that's really interesting. I'm definitely seeing more than just some minor rescaling, I'm pretty sure the image is getting reduce to 1080p. Here's a photo of the screen based on the test image I linked, you can see all the background pixels are exactly the same, which is exactly what would happen if it was scaled down by a factor of 2 in each dimension.
https://photos.app.goo.gl/pBg6jRYYt6Bph4Yv6

Is there any kind of debug log I could access which might give more information? It seems quite possible the issue is either with the image Google is returning, or maybe even with the LG TV trying to do something smart. I might try a different Google account, and also try plugging the Roku into my (also 4k) computer monitor to see if anything is different. I'll report back.

**Comment by hbmcmahan** [comment]
Ok, I tried both the steps I mentioned above (using a separate account, and using a different monitor), both individually and together. I see the same low-resolution problem in all cases.

@chtaylo2, is there a way I can generate a URL to test what Google is sending back from my account directly? Any other ideas?
