### ISSUE TITLE
I only want to show one picture

### ISSUE THREAD

**Issue by Dickeys1603** [chtaylo2/Roku-GooglePhotos#338]
I have an album with only one picture in it I want displayed. I open the app, select that album, which shows only the one picture. after a time, it opens all other albums in my google account. I only selected the ONE album, and that is the ONLY album I am trying to display - with only ONE picture in it, yet it keeps changing to other albums/pictures.

Is there a way to force it to not shuffle or change albums? I set the timer to 999 in hopes that it will work, but I am still waiting... after 999 seconds it opened a different album, so that wasn't the solution.
Thanks in advance!

**Comment by chtaylo2** [comment]
Is this during screensaver playback or within the app itself? Showing only 1 image is troublesome because Roku forbids applications from disabling the screensaver if nothing on the screen is changing. It's a requirement from Roku.

To get around this, you could create an album with 1 photo, select only that album for screensaver playback. See #2 here -> https://www.photoviewapp.com/faq/

OR use that 1 album within the app and disable your screensaver.

**Comment by wmutschler** [comment]
I have used this work around to display 1 image.  It works with one
potential drawback.  The roku screensaver times out after 12 hours and
rolls to a "screen saver timed out" screen.  At this point, you need to
take roku back to home screen and wait for screensaver to reopen (I set
mine to 1 minute delay for screensaver)
