### ISSUE TITLE
API Error - Connection timeout most likely

### ISSUE THREAD

**Issue by mrinot** [chtaylo2/Roku-GooglePhotos#38]
When I click on My Albums to browse, I receive "API Error.   Invalid return code from Google Photos API.    Exit the channel then try again later."

**Comment by chtaylo2** [comment]
Are you seeing this every time?  Try to go into settings and remove your link, exit / reenter app, and re-register.

**Comment by mrinot** [comment]
Aloha...I see it when I try to access the "albums"...every time.  I have uninstalled the app and reloaded it with the same results.  I am able to "search" for folders and they do display pictures.  

Sent from my Fire

**Comment by mrmchenry** [comment]
I have the same problem.  Search works great, but Albums generates the API error. Are shared albums supported? I have many albums.  My wife's account works fine with very few albums.

**Comment by chtaylo2** [comment]
This error is due to an unknown status code back from Google's API.

I'll need some additional details. Could each of you please login to http://photos.google.com and then make the following https request:

https://picasaweb.google.com/data/feed/api/user/default?fields=entry%28title%2Cgphoto%3Anumphotos%2Cgphoto%3Auser%2Cgphoto%3Aid%2Cmedia%3Agroup%28media%3Adescription%2Cmedia%3Athumbnail%29%29&kind=album&thumbsize=220&v=2.0

You can then post the raw source back to this Issue #38. 

@mrmchenry - Shared albums is not currently supported due to an unfortunate limitation in Google's API. If they add support, we'll certainly add it to this channel. (see: https://developers.google.com/picasa-web/faq  - _How is the Picasa Web Albums Data API related to Google Photos?_)

**Comment by mrmchenry** [comment]
[mchenrydump.txt](https://github.com/chtaylo2/Roku-GooglePhotos/files/762304/mchenrydump.txt)

**Comment by chtaylo2** [comment]
I was not able to duplicate the issue using your dump directly. However when I added some latency, I can duplicate the error. My guess (only speculation) is due to the 280+ albums in your account, it's taking over 10 seconds to pull the request back from Google.

Does your Roku have a strong internet connection? Currently the timeout is at 10 seconds; I can increase this to 20 which should help.  Once v1.6 has been approved by Roku (i hope this week), I can give you a custom channel to add & test with this additional timeout. Stay tuned.

**Comment by chtaylo2** [comment]
Bug fix in v.3.765.20170208 - https://github.com/chtaylo2/Roku-GooglePhotos/commit/7634af5a0ba62778a859b41bf5a72b6b0b1ed09f

Will release patch fix prior to 1.7 official release.

**Comment by chtaylo2** [comment]
Moved to release v1.6

**Comment by mrinot** [comment]
Thanks Chris.

________________________________
