### ISSUE TITLE
Videos will stop and just speed through titles

### ISSUE THREAD

**Issue by ghost** [chtaylo2/Roku-GooglePhotos#423]
so I'll be watching a video out of many in a album and out of nowhere it will stop playing and then it will start going through every video as flash speed almost just switching the title of it over and over.

**Comment by chtaylo2** [comment]
When a video is initially uploaded Google does some unknown, backend processing on their side. The problem is, when Google Photos moved their API from Picasa to Google Photos API (https://picasa.google.com/), they removed all documented ability to stream a movie. Yes, everything.

The only way (some of) your videos are able to stream today is a by using an undocumented workaround we were able to find. By adding an additional parameter to the URL, the video streams vs downloads.

See: https://github.com/chtaylo2/Roku-GooglePhotos/blob/master/components/Slideshow/Browse/Browse.brs#L199-L208

Unfortunately, I have no idea how long this will continue to work, but it's been a couple years, so i'm hopeful it's here to stay.

It's possible the format uploaded by is not supported and that's why it's speeding through titles. If it can't play, the app will try the next video inline.

Thanks,
Chris
