### ISSUE TITLE
Gifs

### ISSUE THREAD

**Issue by cheryl28** [chtaylo2/Roku-GooglePhotos#58]
Is there any plans this app will support animated gifs?

**Comment by chtaylo2** [comment]
The following media file formats are Roku supported:

Video	MKV (H.264), MP4 (H.264), MOV (H.264), WMV (VC-1, firmware 3.1 only)
Music	AAC, MP3, WMA, FLAC (firmware 5.3 and later), WAV (firmware 5.3 and later)
Photo	JPG, PNG, GIF (non-animated)

While Roku supports GIF's (as does this channel) it is only non-animated due to a technical limitation from ROKU.

Thanks
Chris
