### ISSUE TITLE
Photos Will Not Display - Black Screen

### ISSUE THREAD

**Issue by SchoonerEstates** [chtaylo2/Roku-GooglePhotos#79]
Hello,
I am trying to set up a slideshow from photos in my google account. When I log in and link my google account, I can find my albums/thumbnails, but if I try to either start a slideshow or view a single image, the screen displays as totally black. 
Any ideas? This is a new roku, new roku account, new app download. But everything else seems to work normally.

Thank you,

**Comment by SchoonerEstates** [comment]
Okay, I've discovered that this problem is more complicated than I thought. The black screen issue is with any and all photo apps on the Roku, but only when the Roku is plugged in with composite cables instead of HDMI (which, unfortunately, is necessary for what I'm actually trying to do.)

If anyone can give me any insight as to why that is, I'd be extremely grateful. But this is not a problem with the Google PhotoView app.

**Comment by chtaylo2** [comment]
Thats weird, maybe Roku hardware related? Are videos working? It's possible the issue is related to an older version of the Roku UI.  If you're account is linked in PhotoView, go to Settings > Screensaver > PhotoView for GooglePhotos > Preview.  Does this work?

The screensaver is using a newer technology called Screengraph. The full PhotoView channel is being moved to this I'll have a beta version out in the next week or so.

You also might want to ask the broader Roku community: https://forums.roku.com/viewforum.php?f=28

/Chris

**Comment by SchoonerEstates** [comment]
Yes, I was able to confirm yesterday that the Screensaver does work, though, of course, it's not ideal given that the pictures are not full screen and I can't select a specific folder. And yes, videos are working.

Is there any way I can get ahold of the beta version when you release it, to see if that fixes the issue?

**Comment by chtaylo2** [comment]
Here's the beta version: https://my.roku.com/account/add?channel=RZ5TQ6

Let me know if this fixes the issue you're seeing.  And RE: Pictures not full screen in screensaver, you can change that in the Custom Screensaver settings.
